# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_window(object):
    def setupUi(self, Login_window, funcion_button):
        Login_window.setObjectName("Login_window")
        Login_window.resize(282, 368)
        Login_window.setMinimumSize(QtCore.QSize(282, 368))
        Login_window.setMaximumSize(QtCore.QSize(282, 368))
        Login_window.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(Login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.Username_textbox = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Username_textbox.sizePolicy().hasHeightForWidth())
        self.Username_textbox.setSizePolicy(sizePolicy)
        self.Username_textbox.setMinimumSize(QtCore.QSize(120, 0))
        self.Username_textbox.setMaximumSize(QtCore.QSize(175, 16777215))
        self.Username_textbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Username_textbox.setInputMask("")
        self.Username_textbox.setText("")
        self.Username_textbox.setObjectName("Username_textbox")

        self.horizontalLayout_2.addWidget(self.Username_textbox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.password_textbox = QtWidgets.QLineEdit(self.centralwidget)
        self.password_textbox.setMinimumSize(QtCore.QSize(120, 0))
        self.password_textbox.setMaximumSize(QtCore.QSize(175, 16777215))
        self.password_textbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_textbox.setObjectName("password_textbox")
        self.password_textbox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_3.addWidget(self.password_textbox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.Login_pushbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Login_pushbutton.sizePolicy().hasHeightForWidth())
        self.Login_pushbutton.setSizePolicy(sizePolicy)
        self.Login_pushbutton.setMinimumSize(QtCore.QSize(225, 0))
        self.Login_pushbutton.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Login_pushbutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Login_pushbutton.setObjectName("Login_pushbutton")

        self.Login_pushbutton.clicked.connect(funcion_button)

        self.horizontalLayout_4.addWidget(self.Login_pushbutton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        Login_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login_window)
        self.statusbar.setObjectName("statusbar")
        Login_window.setStatusBar(self.statusbar)

        self.retranslateUi(Login_window)
        QtCore.QMetaObject.connectSlotsByName(Login_window)

    def getUsernamePassword(self):
        username = self.Username_textbox.text()
        password = self.password_textbox.text()
        #print(password)
        return (username,password)

    def retranslateUi(self, Login_window):
        _translate = QtCore.QCoreApplication.translate
        Login_window.setWindowTitle(_translate("Login_window", "Iniciar sesion"))
        self.label.setText(_translate("Login_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"logo-policia.png\"  width=\"250\" height=\"201\" alt=\"Logo PN\"/></p></body></html>"))
        self.label_3.setText(_translate("Login_window", "<html><head/><body><p><span style=\" color:#000000;\">Nombre de usuario: </span></p></body></html>"))
        self.label_2.setText(_translate("Login_window", "<html><head/><body><p><span style=\" color:#000000;\">Contraseña: </span></p></body></html>"))
        self.Login_pushbutton.setText(_translate("Login_window", "ENTRAR"))
#import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_window = QtWidgets.QMainWindow()
    ui = Ui_Login_window()
    ui.setupUi(Login_window)
    Login_window.show()
    sys.exit(app.exec_())
